### ISSUE TITLE
[ZEON] - recommended additions

### ISSUE THREAD

**Issue by zeon-neon** [NeonGamerBot-QK/hackclub-verification#1]
# Meta

- [ ] Github repo has no description [enable here](https://github.com/NeonGamerBot-QK/hackclub-verification)

- [ ] There is no homepage! [enable here](https://github.com/NeonGamerBot-QK/hackclub-verification)

- [ ] Your repo does not have web commit signing off enabled. **PLEASE ENABLE IT** [here](https://github.com/NeonGamerBot-QK/hackclub-verification/settings)

- [ ] This repo does not have discussions enabled

- [ ] This repo does not have a code of conduct
# Automation

- [x] **Mark this to override & close this issue.**
